spring.application.name=seguridadcalidad
server.port=8002
server.servlet.context-path=/recetas
backend.url=${BACKEND_URL:http://localhost:8081}

# A01:2021 - Forzar el uso exclusivo de cookies para la sesión
server.servlet.session.tracking-modes=cookie
# Evitar que el ID de sesión sea accesible por scripts (Mitiga XSS)
server.servlet.session.cookie.http-only=true